version: '3'

tasks:
  3rdparty:python:update:
    desc: Update lockfile for third party Python dependencies
    cmds:
      - pants generate-lockfiles

  3rdparty:python:venv:
    desc: Create a virtual environment for third party Python dependencies
    cmds:
      - pants export

  prepare:
    desc: Prepare the build
    cmds:
      - pants run python/generate_state.py -- aider-chat
      - pants run python/generate_releases.py -- aider-chat
      - pants run python/generate_requirements.py -- aider-chat

  build:
    desc: Build the PEX
    cmds:
      - pants run python/generate_pex.py -- aider-chat

  finalize:
    desc: Finalize the build
    cmds:
      - pants run python/generate_build_info.py -- aider-chat
      - pants run python/generate_hermit_manifest.py -- aider-chat

  all:
    desc: Run all tasks
    cmds:
      - task: prepare
      - task: build
      - task: finalize
    