version: '3'

tasks:
  3rdparty:python:update:
    desc: Update lockfile for third party Python dependencies
    cmds:
      - pants generate-lockfiles

  3rdparty:python:venv:
    desc: Create a virtual environment for third party Python dependencies
    cmds:
      - pants export

  pex:build:
    desc: Run the PEX package builder
    cmds:
      - pants run python:build_pex_packages -- aider-chat

  pex:finalize:
    desc: Finalize the PEX packages
    cmds:
      - pants run python:finalize_releases -- aider-chat

  pex:manifest:
    desc: Generate the Hermit manifest
    cmds:
      - pants run python:generate_hermit_manifests -- aider-chat