binaries:
  - aider
package: aider-chat

versions:
  # Using Python 3.11, because `google-generativeai` depends on pkg_resources which is removed in Python 3.12
  # Doesn't seem to matter. So maybe just exclude that particular library??
  - version: 0.83.1
    python: "3.10"
