package: aider-chat
test: "aider --help"
description: "Aider is a command-line tool that helps you write better code by providing real-time feedback and suggestions as you type."
binaries:
  - aider

versions:
  # Using Python 3.11, because `google-generativeai` depends on pkg_resources which is removed in Python 3.12
  # Doesn't seem to matter. So maybe just exclude that particular library??

  # latest: 0.83.1
  - version: 0.82.3
    python: "3.10"
