package: aider-chat
test: "aider --help"
description: "Aider is a command-line tool that helps you write better code by providing real-time feedback and suggestions as you type."
binaries:
  - aider

versions:
  # Using Python 3.11 for compatibility with all dependencies
  - version: 0.80.0
    python: "3.11 "
