package: aider-chat
# Adding setuptools to prevent deprecation warnings when launching aider
extra_packages:
  - setuptools>=71.0.2,<80.9
config_version: 2
test: "aider --help"
description: "Aider is a command-line tool that helps you write better code by providing real-time feedback and suggestions as you type."
binaries:
  - aider

versions:
  # Using Python 3.11 for compatibility with all dependencies
  - version: 0.82.0
    python: "3.11"

  # # Only the latest version
  # - version: 0.83.1
  #   python: "3.11"
