name: Build PEX Packages

on:
  push:
    branches:
      - main

# Cancel in-progress runs of this workflow when a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build PEX packages
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write  # Required for creating GitHub releases
    strategy:
      matrix:
        os: 
          - ubuntu-24.04, # amd64
          - ubuntu-24.04-arm64 # arm64
          - macos-13 # amd64
          - macos-15 # arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup environment variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > .env
          
      - uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.1
          masks: GITHUB_TOKEN
          
      - uses: cashapp/activate-hermit@v1

      - name: Build PEX packages
        run: |
          task pex:build
